/**
 * @fileoverview Generated court-id -> CourtListener `full_name` map. Built once
 * from a live `/courts/?in_use=true` snapshot (471 in-use courts) so court-name
 * resolution stays local with no per-request API cost — which matters under the
 * free-tier rate limit (5 req/min). `full_name` values are verbatim from the API.
 *
 * Regenerate from a fresh `/courts/` snapshot if CourtListener adds/renames courts.
 * @module services/courtlistener/court-names-data
 */

/** CourtListener court id -> official `full_name` (in-use courts). */
export const COURT_FULL_NAMES: Record<string, string> = {
  acca: 'Army Court of Criminal Appeals',
  afcca: 'United States Air Force Court of Criminal Appeals',
  akb: 'United States Bankruptcy Court, D. Alaska',
  akd: 'District Court, D. Alaska',
  ala: 'Supreme Court of Alabama',
  alacivapp: 'Court of Civil Appeals of Alabama',
  alacrimapp: 'Court of Criminal Appeals of Alabama',
  alactapp: 'Alabama Court of Appeals',
  alaska: 'Alaska Supreme Court',
  alaskactapp: 'Court of Appeals of Alaska',
  almb: 'United States Bankruptcy Court, M.D. Alabama',
  almd: 'District Court, M.D. Alabama',
  alnb: 'United States Bankruptcy Court, N.D. Alabama',
  alnd: 'District Court, N.D. Alabama',
  alsb: 'United States Bankruptcy Court, S.D. Alabama',
  alsd: 'District Court, S.D. Alabama',
  amsamoa: 'High Court of American Samoa',
  amsamoatc: 'American Samoa District Court',
  arb: 'United States Bankruptcy Court, D. Arizona',
  areb: 'United States Bankruptcy Court, E.D. Arkansas',
  ared: 'District Court, E.D. Arkansas',
  ariz: 'Arizona Supreme Court',
  arizctapp: 'Court of Appeals of Arizona',
  ariztaxct: 'Arizona Tax Court',
  ark: 'Supreme Court of Arkansas',
  arkag: 'Arkansas Attorney General Reports',
  arkctapp: 'Court of Appeals of Arkansas',
  arkworkcompcom: "Arkansas Workers' Compensation Commission",
  armfor: 'Court of Appeals for the Armed Forces',
  arwb: 'United States Bankruptcy Court, W.D. Arkansas',
  arwd: 'District Court, W.D. Arkansas',
  asbca: 'Armed Services Board of Contract Appeals',
  azd: 'District Court, D. Arizona',
  bap1: 'Bankruptcy Appellate Panel of the First Circuit',
  bap10: 'Bankruptcy Appellate Panel of the Tenth Circuit',
  bap2: 'Bankruptcy Appellate Panel of the Second Circuit',
  bap6: 'Bankruptcy Appellate Panel of the Sixth Circuit',
  bap8: 'United States Bankruptcy Appellate Panel for the Eighth Circuit',
  bap9: 'United States Bankruptcy Appellate Panel for the Ninth Circuit',
  bapma: 'Bankruptcy Appellate Panel of Massachusetts',
  bapme: 'Bankruptcy Appellate Panel, D. Maine',
  bia: 'Board of Immigration Appeals',
  bta: 'United States Board of Tax Appeals',
  bva: "Board of Veterans' Appeals",
  ca1: 'Court of Appeals for the First Circuit',
  ca10: 'Court of Appeals for the Tenth Circuit',
  ca11: 'Court of Appeals for the Eleventh Circuit',
  ca2: 'Court of Appeals for the Second Circuit',
  ca3: 'Court of Appeals for the Third Circuit',
  ca4: 'Court of Appeals for the Fourth Circuit',
  ca5: 'Court of Appeals for the Fifth Circuit',
  ca6: 'Court of Appeals for the Sixth Circuit',
  ca7: 'Court of Appeals for the Seventh Circuit',
  ca8: 'Court of Appeals for the Eighth Circuit',
  ca9: 'Court of Appeals for the Ninth Circuit',
  cacb: 'United States Bankruptcy Court, C.D. California',
  cacd: 'District Court, C.D. California',
  cadc: 'Court of Appeals for the D.C. Circuit',
  caeb: 'United States Bankruptcy Court, E.D. California',
  caed: 'District Court, E.D. California',
  cafc: 'Court of Appeals for the Federal Circuit',
  cal: 'California Supreme Court',
  calag: 'California Attorney General Reports',
  calappdeptsuper: 'Appellate Division of the Superior Court of California',
  calctapp: 'California Court of Appeal',
  californiad: 'District Court, D. California',
  canalzoned: 'District Court, Canal Zone',
  canb: 'United States Bankruptcy Court, N.D. California',
  cand: 'District Court, N.D. California',
  casb: 'United States Bankruptcy Court, S.D. California',
  casd: 'District Court, S.D. California',
  cavc: 'United States Court of Appeals for Veterans Claims',
  cc: 'United States Court of Claims',
  ccpa: 'Court of Customs and Patent Appeals',
  cgcomilrev: 'U S Coast Guard Court of Military Review',
  cherokee: 'Cherokee Nation Supreme Court',
  cherokeeapp: 'Cherokee Nation Judicial Appeals Tribunal',
  cherokeetribct: 'Cherokee Indian Tribal Court',
  cheyrsiouxctapp: 'Cheyenne River Sioux Tribal Court of Appeals',
  cit: 'United States Court of International Trade',
  cjdpa: 'Court of Judicial Discipline of Pennsylvania',
  cma: 'United States Court of Military Appeals',
  cnmisuperct: 'Northern Mariana Islands Commonwealth Superior Court',
  cnmitrialct: 'Northern Mariana Islands Commonwealth Trial Court',
  cob: 'United States Bankruptcy Court, D. Colorado',
  cod: 'District Court, D. Colorado',
  colo: 'Supreme Court of Colorado',
  coloag: 'Colorado Attorney General Reports',
  coloctapp: 'Colorado Court of Appeals',
  coloworkcompcom: 'Colorado Industrial Claim Appeals Office',
  colvctapp: 'Colville Confederated Court of Appeals',
  com: 'Commerce Court',
  conn: 'Supreme Court of Connecticut',
  connappct: 'Connecticut Appellate Court',
  connsuperct: 'Connecticut Superior Court',
  connworkcompcom: 'Connecticut Compensation Review Board',
  coquct: 'Coquille Indian Tribal Court',
  ctb: 'United States Bankruptcy Court, D. Connecticut',
  ctd: 'District Court, D. Connecticut',
  cusc: 'United States Customs Court',
  dc: 'District of Columbia Court of Appeals',
  dcb: 'United States Bankruptcy Court, District of Columbia',
  dcd: 'District Court, District of Columbia',
  deb: 'United States Bankruptcy Court, D. Delaware',
  ded: 'District Court, D. Delaware',
  del: 'Supreme Court of Delaware',
  delch: 'Court of Chancery of Delaware',
  delctcompl: 'Delaware Court of Common Pleas',
  delfamct: 'Delaware Family Court',
  deljudct: 'Court on the Judiciary of Delaware.',
  delorphct: "Orphan's Court of Delaware",
  delsuperct: 'Superior Court of Delaware',
  eca: 'Emergency Court of Appeals',
  echerkokee: 'Eastern Band of Cherokee Indians Supreme Court',
  echerokeect: 'Eastern Band of Cherokee Indians Tribal Court',
  fisc: 'Foreign Intelligence Surveillance Court',
  fiscr: 'Foreign Intelligence Surveillance Court of Review',
  fla: 'Supreme Court of Florida',
  flaag: 'Florida Attorney General Reports',
  fladistctapp: 'District Court of Appeal of Florida',
  flmb: 'United States Bankruptcy Court, M.D. Florida',
  flmd: 'District Court, M.D. Florida',
  flnb: 'United States Bankruptcy Court, N.D. Florida',
  flnd: 'District Court, N.D. Florida',
  flsb: 'United States Bankruptcy Court, S.D. Florida.',
  flsd: 'District Court, S.D. Florida',
  ftmcdowctapp: 'Fort McDowell Yavapai Nation Tribal Court of Appeals',
  ftmcdowell: 'Fort McDowell Supreme Court',
  ftpeckctapp: 'Fort Peck Appellate Court',
  ftpecktrialct: 'Fort Peck Tribal Court',
  ga: 'Supreme Court of Georgia',
  gactapp: 'Court of Appeals of Georgia',
  gamb: 'United States Bankruptcy Court, M.D. Georgia',
  gamd: 'District Court, M.D. Georgia',
  ganb: 'United States Bankruptcy Court, N.D. Georgia',
  gand: 'District Court, N.D. Georgia',
  gasb: 'United States Bankruptcy Court, S.D. Georgia',
  gasd: 'District Court, S.D. Georgia',
  grrondect: 'Grand Ronde Tribal Court',
  grrondectapp: 'Grand Ronde Court of Appeals',
  grtravbandct: 'Grand Traverse Band of Ottawa and Chippewa Indians Tribal Court',
  grtravbandctapp: 'Grand Traverse Band of Ottawa & Chippewa Indians Tribal Appellate Court',
  guam: 'Supreme Court of Guam',
  gub: 'United States Bankruptcy Court, D. Guam',
  gud: 'District Court, D. Guam',
  haw: 'Hawaii Supreme Court',
  hawapp: 'Hawaii Intermediate Court of Appeals',
  hib: 'United States Bankruptcy Court, D. Hawaii',
  hid: 'District Court, D. Hawaii',
  hochunk: 'Ho-Chunk Nation Supreme Court',
  hochunkct: 'Ho-Chunk Nation Trial Court',
  hopiappct: 'Hopi Appellate Court',
  ianb: 'United States Bankruptcy Court, N.D. Iowa',
  iand: 'District Court, N.D. Iowa',
  iasb: 'United States Bankruptcy Court, S.D. Iowa',
  iasd: 'District Court, S.D. Iowa',
  idaho: 'Idaho Supreme Court',
  idahoctapp: 'Idaho Court of Appeals',
  idb: 'United States Bankruptcy Court, D. Idaho',
  idd: 'District Court, D. Idaho',
  ilcb: 'United States Bankruptcy Court, C.D. Illinois',
  ilcd: 'District Court, C.D. Illinois',
  ill: 'Illinois Supreme Court',
  illappct: 'Appellate Court of Illinois',
  illinoisd: 'District Court, D. Illinois',
  illinoised: 'District Court, E.D. Illinois',
  ilnb: 'United States Bankruptcy Court, N.D. Illinois',
  ilnd: 'District Court, N.D. Illinois',
  ilsb: 'United States Bankruptcy Court, S.D. Illinois',
  ilsd: 'District Court, S.D. Illinois',
  ind: 'Indiana Supreme Court',
  indctapp: 'Indiana Court of Appeals',
  indianad: 'District Court, D. Indiana',
  indtc: 'Indiana Tax Court',
  innb: 'United States Bankruptcy Court, N.D. Indiana',
  innd: 'District Court, N.D. Indiana',
  insb: 'United States Bankruptcy Court, S.D. Indiana',
  insd: 'District Court, S.D. Indiana',
  iowa: 'Supreme Court of Iowa',
  iowactapp: 'Court of Appeals of Iowa',
  jpml: 'United States Judicial Panel on Multidistrict Litigation',
  kan: 'Supreme Court of Kansas',
  kanag: 'Kansas Attorney General Reports',
  kanctapp: 'Court of Appeals of Kansas',
  kingsbench: "Court of King's Bench",
  ksb: 'United States Bankruptcy Court, D. Kansas',
  ksd: 'District Court, D. Kansas',
  ky: 'Kentucky Supreme Court',
  kyctapp: 'Court of Appeals of Kentucky',
  kyctapphigh: 'Court of Appeals of Kentucky (pre-1976)',
  kyeb: 'United States Bankruptcy Court, E.D. Kentucky',
  kyed: 'District Court, E.D. Kentucky',
  kywb: 'United States Bankruptcy Court, W.D. Kentucky',
  kywd: 'District Court, W.D. Kentucky',
  la: 'Supreme Court of Louisiana',
  laag: 'Louisiana Attorney General Reports',
  lactapp: 'Louisiana Court of Appeal',
  laeb: 'United States Bankruptcy Court, E.D. Louisiana',
  laed: 'District Court, E.D. Louisiana',
  lamb: 'United States Bankruptcy Court, M.D. Louisiana',
  lamd: 'District Court, M.D. Louisiana',
  lawb: 'United States Bankruptcy Court, W.D. Louisiana',
  lawd: 'District Court, W.D. Louisiana',
  leechojibtr: 'Leech Lake Band of Ojibwe Tribal Court',
  lrbottawact: 'Little River Band of Ottawa Indians Tribal Court',
  lrbottawactapp: 'Little River Band of Ottawa Indians Tribal Court of Appeals',
  mab: 'United States Bankruptcy Court, D. Massachusetts',
  mad: 'District Court, D. Massachusetts',
  mass: 'Massachusetts Supreme Judicial Court',
  massappct: 'Massachusetts Appeals Court',
  massdistct: 'Massachusetts District Court',
  masslandct: 'Massachusetts Land Court',
  masssuperct: 'Massachusetts Superior Court',
  maworkcompcom: 'Massachusetts Department of Industrial Accidents',
  mc: 'United States Court of Military Commission Review',
  md: 'Court of Appeals of Maryland',
  mdag: 'Maryland Attorney General Reports',
  mdb: 'United States Bankruptcy Court, D. Maryland',
  mdch: 'High Court of Chancery of Maryland',
  mdctspecapp: 'Court of Special Appeals of Maryland',
  mdd: 'District Court, D. Maryland',
  me: 'Supreme Judicial Court of Maine',
  meb: 'United States Bankruptcy Court, D. Maine',
  med: 'District Court, D. Maine',
  mesuperct: 'Superior Court of Maine',
  mich: 'Michigan Supreme Court',
  michctapp: 'Michigan Court of Appeals',
  mieb: 'United States Bankruptcy Court, E.D. Michigan',
  mied: 'District Court, E.D. Michigan',
  minn: 'Supreme Court of Minnesota',
  minnag: 'Minnesota Attorney General Reports',
  minnctapp: 'Court of Appeals of Minnesota',
  miss: 'Mississippi Supreme Court',
  missctapp: 'Court of Appeals of Mississippi',
  miwb: 'United States Bankruptcy Court, W.D. Michigan',
  miwd: 'District Court, W.D. Michigan',
  mnb: 'United States Bankruptcy Court, D. Minnesota',
  mnd: 'District Court, D. Minnesota',
  mo: 'Supreme Court of Missouri',
  moag: 'Missouri Attorney General Reports',
  moctapp: 'Missouri Court of Appeals',
  moeb: 'United States Bankruptcy Court, E.D. Missouri',
  moed: 'District Court, E.D. Missouri',
  moheganct: 'Mohegan Trial Court',
  moheganctapp: 'Mohegan Tribal Court of Appeals',
  moheganelders: 'Council of Elders of the Mohegan Tribe',
  mohegangct: 'Mohegan Gaming Disputes Trial Court',
  mohegangctapp: 'Mohegan Gaming Disputes Court of Appeals',
  mont: 'Montana Supreme Court',
  montag: 'Montana Attorney General Reports',
  monttc: 'Montana Tax Appeal Board',
  mowb: 'United States Bankruptcy Court, W.D. Missouri',
  mowd: 'District Court, W.D. Missouri',
  msnb: 'United States Bankruptcy Court, N.D. Mississippi',
  msnd: 'District Court, N.D. Mississippi',
  mspb: 'Merit Systems Protection Board',
  mssb: 'United States Bankruptcy Court, S.D. Mississippi',
  mssd: 'District Court, S.D. Mississippi',
  mtb: 'United States Bankruptcy Court, D. Montana',
  mtd: 'District Court, D. Montana',
  navajo: 'Navajo Nation Supreme Court',
  navajochildct: "Navajo Nation Children's Court",
  navajoctapp: 'Navajo Nation Court of Appeals',
  navajofamct: 'Navajo Nation Family Court',
  nc: 'Supreme Court of North Carolina',
  ncbizct: 'North Carolina Business Court',
  ncctapp: 'Court of Appeals of North Carolina',
  nceb: 'United States Bankruptcy Court, E.D. North Carolina',
  nced: 'District Court, E.D. North Carolina',
  ncmb: 'United States Bankruptcy Court, M.D. North Carolina',
  ncmd: 'District Court, M.D. North Carolina',
  ncsuperct: 'Superior Court of North Carolina',
  ncwb: 'United States Bankruptcy Court, W.D. North Carolina',
  ncwd: 'District Court, W.D. North Carolina',
  ncworkcompcom: 'North Carolina Industrial Commission',
  nd: 'North Dakota Supreme Court',
  ndb: 'United States Bankruptcy Court, D. North Dakota',
  ndctapp: 'North Dakota Court of Appeals',
  ndd: 'District Court, D. North Dakota',
  neb: 'Nebraska Supreme Court',
  nebag: 'Nebraska Attorney General Reports',
  nebctapp: 'Nebraska Court of Appeals',
  nebraskab: 'United States Bankruptcy Court, D. Nebraska',
  ned: 'District Court, D. Nebraska',
  nev: 'Nevada Supreme Court',
  nevapp: 'Court of Appeals of Nevada',
  nh: 'Supreme Court of New Hampshire',
  nhb: 'United States Bankruptcy Court, D. New Hampshire',
  nhd: 'District Court, D. New Hampshire',
  nj: 'Supreme Court of New Jersey',
  njb: 'United States Bankruptcy Court, D. New Jersey',
  njch: 'New Jersey Court of Chancery',
  njd: 'District Court, D. New Jersey',
  njsuperctappdiv: 'New Jersey Superior Court Appellate Division',
  njtaxct: 'New Jersey Tax Court',
  nm: 'New Mexico Supreme Court',
  nmariana: 'Supreme Court of The Commonwealth of The Northern Mariana Islands',
  nmb: 'United States Bankruptcy Court, D. New Mexico',
  nmcca: 'Navy-Marine Corps Court of Criminal Appeals',
  nmctapp: 'New Mexico Court of Appeals',
  nmd: 'District Court, D. New Mexico',
  nmib: 'United States Bankruptcy Court, Northern Mariana Islands',
  nmid: 'District Court, Northern Mariana Islands',
  nvb: 'United States Bankruptcy Court, D. Nevada',
  nvd: 'District Court, D. Nevada',
  ny: 'New York Court of Appeals',
  nyag: 'New York Attorney General Reports',
  nyappdiv: 'Appellate Division of the Supreme Court of the State of New York',
  nyappterm: 'Appellate Terms of the Supreme Court of New York',
  nycivct: 'Civil Court of the City of New York',
  nycountyct: 'New York County Courts',
  nycrimct: 'Criminal Court of the City of New York',
  nydistct: 'New York District Court',
  nyeb: 'United States Bankruptcy Court, E.D. New York',
  nyed: 'District Court, E.D. New York',
  nyfamct: 'New York Family Court',
  nyjustct: 'New York Justice Court',
  nynb: 'United States Bankruptcy Court, N.D. New York',
  nynd: 'District Court, N.D. New York',
  nysb: 'United States Bankruptcy Court, S.D. New York',
  nysd: 'District Court, S.D. New York',
  nysupct: 'New York Supreme Court',
  nysurct: "New York Surrogate's Court",
  nywb: 'United States Bankruptcy Court, W.D. New York',
  nywd: 'District Court, W.D. New York',
  odawactapp: 'Little Traverse Bay Bands of Odawa Indians Tribal Appellate Court',
  ohio: 'Ohio Supreme Court',
  ohioctapp: 'Ohio Court of Appeals',
  ohioctcl: 'Ohio Court of Claims',
  ohiod: 'District Court, D. Ohio',
  ohnb: 'United States Bankruptcy Court, N.D. Ohio',
  ohnd: 'District Court, N.D. Ohio',
  ohsb: 'United States Bankruptcy Court, S.D. Ohio',
  ohsd: 'District Court, S.D. Ohio',
  okeb: 'United States Bankruptcy Court, E.D. Oklahoma',
  oked: 'District Court, E.D. Oklahoma',
  okla: 'Supreme Court of Oklahoma',
  oklaag: 'Oklahoma Attorney General Reports',
  oklacivapp: 'Court of Civil Appeals of Oklahoma',
  oklacoj: 'Court on the Judiciary of Oklahoma',
  oklacrimapp: 'Court of Criminal Appeals of Oklahoma',
  oklajeap: 'Oklahoma Judicial Ethics Advisory Panel',
  oknb: 'United States Bankruptcy Court, N.D. Oklahoma',
  oknd: 'District Court, N.D. Oklahoma',
  okwb: 'United States Bankruptcy Court, W.D. Oklahoma',
  okwd: 'District Court, W.D. Oklahoma',
  olc: 'Department of Justice Office of Legal Counsel',
  oneidactapp: 'Oneida Appellate Court',
  oneidatrialct: 'Oneida Tribal Judicial System, Trial Court',
  or: 'Oregon Supreme Court',
  orb: 'United States Bankruptcy Court, D. Oregon',
  orctapp: 'Court of Appeals of Oregon',
  ord: 'District Court, D. Oregon',
  orld: 'District Court, Orleans',
  ortc: 'Oregon Tax Court',
  pa: 'Supreme Court of Pennsylvania',
  pacommwct: 'Commonwealth Court of Pennsylvania',
  paeb: 'United States Bankruptcy Court, E.D. Pennsylvania',
  paed: 'District Court, E.D. Pennsylvania',
  pamb: 'United States Bankruptcy Court, M.D. Pennsylvania',
  pamd: 'District Court, M.D. Pennsylvania',
  pasuperct: 'Superior Court of Pennsylvania',
  pawb: 'United States Bankruptcy Court, W.D. Pennsylvania',
  pawd: 'District Court, W.D. Pennsylvania',
  pennsylvaniad: 'District Court, D. Pennsylvania',
  prapp: 'Tribunal De Apelaciones De Puerto Rico/Court of Appeals of Puerto Rico',
  prb: 'United States Bankruptcy Court, D. Puerto Rico',
  prd: 'District Court, D. Puerto Rico',
  prsupreme: 'Supreme Court of Puerto Rico',
  reglrailreorgct: 'Special Court under the Regional Rail Reorganization Act',
  ri: 'Supreme Court of Rhode Island',
  rib: 'United States Bankruptcy Court, D. Rhode Island',
  rid: 'District Court, D. Rhode Island',
  risuperct: 'Superior Court of Rhode Island',
  sacfoxdistct: 'Sac and Fox Nation District Court',
  sacfoxsupct: 'Sac and Fox Nation Supreme Court',
  salishctapp: 'Confederated Salish & Kootenai Court of Appeals',
  sc: 'Supreme Court of South Carolina',
  scb: 'United States Bankruptcy Court, D. South Carolina',
  scctapp: 'Court of Appeals of South Carolina',
  scd: 'District Court, D. South Carolina',
  scotus: 'Supreme Court of the United States',
  sd: 'South Dakota Supreme Court',
  sdb: 'United States Bankruptcy Court, D. South Dakota',
  sdd: 'District Court, D. South Dakota',
  shoaraphotr: 'Shoshone and Arapaho Tribal Court',
  southcarolinaed: 'District Court, E.D. South Carolina',
  southcarolinawd: 'District Court, W.D. South Carolina',
  swinomishappct: 'Swinomish Tribal Court of Appeals',
  swinomishtr: 'Swinomish Tribal Court',
  tax: 'United States Tax Court',
  tecoa: 'Temporary Emergency Court of Appeals',
  tenn: 'Tennessee Supreme Court',
  tenncrimapp: 'Court of Criminal Appeals of Tennessee',
  tennctapp: 'Court of Appeals of Tennessee',
  tennessed: 'District Court, D. Tennessee',
  tennesseeb: 'United States Bankruptcy Court, D. Tennessee',
  tennsuperct: 'Tennessee Superior Court for Law and Equity',
  tennworkcompapp: "Tennessee Workers' Compensation Appeals Board",
  tennworkcompcl: "Tennessee Court of Workers' Compensation Claims",
  tex: 'Texas Supreme Court',
  texag: 'Texas Attorney General Reports',
  texapp: 'Court of Appeals of Texas',
  texbizct: 'Texas Business Court',
  texcrimapp: 'Court of Criminal Appeals of Texas',
  texjpml: 'Texas Judicial Panel on Multidistrict Litigation',
  texreview: 'Texas Special Court of Review',
  tneb: 'United States Bankruptcy Court, E.D. Tennessee',
  tned: 'District Court, E.D. Tennessee',
  tnmb: 'United States Bankruptcy Court, M.D. Tennessee',
  tnmd: 'District Court, M.D. Tennessee',
  tnwb: 'United States Bankruptcy Court, W.D. Tennessee',
  tnwd: 'District Court, W.D. Tennessee',
  ttab: 'Trademark Trial and Appeal Board',
  tulalipctapp: 'Tulalip Court of Appeals',
  txeb: 'United States Bankruptcy Court, E.D. Texas',
  txed: 'District Court, E.D. Texas',
  txnb: 'United States Bankruptcy Court, N.D. Texas',
  txnd: 'District Court, N.D. Texas',
  txsb: 'United States Bankruptcy Court, S.D. Texas',
  txsd: 'District Court, S.D. Texas',
  txwb: 'United States Bankruptcy Court, W.D. Texas',
  txwd: 'District Court, W.D. Texas',
  usafctmilrev: 'U S Air Force Court of Military Review',
  usarmymilrev: 'U.S. Army Court of Military Review',
  uscfc: 'United States Court of Federal Claims',
  uscgcoca: 'U S Coast Guard Court of Criminal Appeals',
  usjc: 'United States Judicial Conference Committee',
  usnmcmilrev: 'U.S. Navy-Marine Corps Court of Military Review',
  utah: 'Utah Supreme Court',
  utahctapp: 'Court of Appeals of Utah',
  utb: 'United States Bankruptcy Court, D. Utah',
  utd: 'District Court, D. Utah',
  va: 'Supreme Court of Virginia',
  vactapp: 'Court of Appeals of Virginia',
  vaeb: 'United States Bankruptcy Court, E.D. Virginia',
  vaed: 'District Court, E.D. Virginia',
  vawb: 'United States Bankruptcy Court, W.D. Virginia',
  vawd: 'District Court, W.D. Virginia',
  vib: 'United States Bankruptcy Court, D. Virgin Islands',
  vid: 'District Court, Virgin Islands',
  virginislands: 'Supreme Court of The Virgin Islands',
  vt: 'Supreme Court of Vermont',
  vtb: 'United States Bankruptcy Court, D. Vermont',
  vtd: 'District Court, D. Vermont',
  vtsuperct: 'Vermont Superior Court',
  waeb: 'United States Bankruptcy Court, E.D. Washington',
  waed: 'District Court, E.D. Washington',
  wash: 'Washington Supreme Court',
  washag: 'Washington Attorney General Reports',
  washctapp: 'Court of Appeals of Washington',
  washterr: 'Washington Territory',
  wawb: 'United States Bankruptcy Court, W.D. Washington',
  wawd: 'District Court, W.D. Washington',
  webchippewatr: 'White Earth Band of Chippewa Tribal Court',
  wieb: 'United States Bankruptcy Court, E.D. Wisconsin',
  wied: 'District Court, E.D. Wisconsin',
  wis: 'Wisconsin Supreme Court',
  wisag: 'Wisconsin Attorney General Reports',
  wisctapp: 'Court of Appeals of Wisconsin',
  wiwb: 'United States Bankruptcy Court, W.D. Wisconsin',
  wiwd: 'District Court, W.D. Wisconsin',
  wva: 'West Virginia Supreme Court',
  wvactapp: 'Intermediate Court of Appeals of West Virginia',
  wvnb: 'United States Bankruptcy Court, N.D. West Virginia',
  wvnd: 'District Court, N.D. West Virginia',
  wvsb: 'United States Bankruptcy Court, S.D. West Virginia',
  wvsd: 'District Court, S.D. West Virginia',
  wyb: 'United States Bankruptcy Court, D. Wyoming',
  wyd: 'District Court, D. Wyoming',
  wyo: 'Wyoming Supreme Court',
};
